# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Leanovate Presentation"
license = "MIT"
licenselink = "https://github.com/leanovate/leanovate-presentation-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/leanovate/leanovate-presentation-theme"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[taxonomies]
  presentation = "presentations"
